import type { Player } from "./types";

export const SEED_PLAYERS: Player[] = [
  {
    id: "p-you",
    payCashApp: "upsetyou",
    payVenmo: "upset-you",
    payZelle: "you@example.com",

    photoUrl: "/players/p-you.jpg?v=fb3",
    name: "You",
    handle: "you",
    city: "Austin",
    heightIn: 72,
    weightLb: 175,
    experienceYears: 4,
    rating: 1520,
    gamesPlayed: 20,
    sportsmanship: 4.6,
    reliability: 4.7,
    wins: 12,
    losses: 8,
    streak: 2,
    homeCourtId: "cat-battle-bend",
    neighborhood: "South Austin",
    availability: "available",
    bio: "Looking for clean 1v1 runs after work.",
    hue: 22,
    quietStart: 22,
    quietEnd: 7,
    pingsToday: 0,
    pingsDate: "",
    ignoreStreak: 0,
    preferredHour: 19,
    lastPlayedAt: new Date(Date.now() - 0 * 864e5).toISOString(),
    openToChallenges: true,
    dmPrivacy: "everyone",
    hideFromCatalog: false,
    age: 28,
    gender: "man" as const,
    ethnicity: "Latino",
    challengesToday: 0,
    challengesDate: "",
    dmFirstToday: 0,
    dmFirstDate: "",
    rankLastWeek: 9,
    pointsScored: 420,
    pointsAllowed: 390,
    weeklyWins: 2,
    weeklyLosses: 1,
    ratingLastWeek: 1490,
  },
  {
    id: "p-sean",
    payCashApp: "seanruns",
    payVenmo: "sean-runs",

    photoUrl: "/players/p-sean.jpg?v=fb3",
    name: "Sean Rivera",
    handle: "seanruns",
    city: "Austin",
    heightIn: 74,
    weightLb: 185,
    experienceYears: 8,
    rating: 1885,
    gamesPlayed: 64,
    sportsmanship: 4.7,
    reliability: 4.9,
    wins: 48,
    losses: 16,
    streak: 5,
    homeCourtId: "cat-givens",
    neighborhood: "East Austin",
    availability: "available",
    bio: "East side. Bring defense.",
    hue: 18,
    quietStart: 23,
    quietEnd: 8,
    pingsToday: 0,
    pingsDate: "",
    ignoreStreak: 0,
    preferredHour: 18,
    lastPlayedAt: new Date(Date.now() - 0 * 864e5).toISOString(),
    openToChallenges: true,
    dmPrivacy: "everyone",
    hideFromCatalog: false,
    age: 29,
    gender: "man" as const,
    ethnicity: "Latino",
    challengesToday: 0,
    challengesDate: "",
    dmFirstToday: 0,
    dmFirstDate: "",
    rankLastWeek: 3,
    pointsScored: 1680,
    pointsAllowed: 1320,
    weeklyWins: 4,
    weeklyLosses: 0,
    ratingLastWeek: 1840,
  },
  {
    id: "p-marcus",
    payCashApp: "marcusatx",
    payVenmo: "marcus-atx",

    photoUrl: "/players/p-marcus.jpg?v=fb3",
    name: "Marcus Hale",
    handle: "mhale",
    city: "Austin",
    heightIn: 76,
    weightLb: 200,
    experienceYears: 10,
    rating: 1840,
    gamesPlayed: 55,
    sportsmanship: 4.8,
    reliability: 4.5,
    wins: 41,
    losses: 14,
    streak: 3,
    homeCourtId: "cat-zilker",
    availability: "available",
    bio: "Post-ups & midrange. Fair fouls only.",
    hue: 198,
    quietStart: 22,
    quietEnd: 7,
    pingsToday: 0,
    pingsDate: "",
    ignoreStreak: 0,
    preferredHour: 19,
    lastPlayedAt: new Date(Date.now() - 1 * 864e5).toISOString(),
    openToChallenges: true,
    dmPrivacy: "everyone",
    hideFromCatalog: false,
    age: 27,
    gender: "man" as const,
    ethnicity: "Black",
    neighborhood: "North Austin",
    challengesToday: 0,
    challengesDate: "",
    dmFirstToday: 0,
    dmFirstDate: "",
    rankLastWeek: 1,
    pointsScored: 1510,
    pointsAllowed: 1180,
    weeklyWins: 3,
    weeklyLosses: 1,
    ratingLastWeek: 1890,
  },
  {
    id: "p-jia",
    photoUrl: "/players/p-jia.jpg?v=fb3",
    name: "Jia Nguyen",
    handle: "jia_n",
    city: "Austin",
    heightIn: 68,
    weightLb: 145,
    experienceYears: 6,
    rating: 1710,
    gamesPlayed: 42,
    sportsmanship: 5.0,
    reliability: 4.8,
    wins: 33,
    losses: 19,
    streak: 1,
    homeCourtId: "cat-pease",
    availability: "available",
    bio: "Handles & threes. Quiet competitor.",
    hue: 280,
    quietStart: 21,
    quietEnd: 8,
    pingsToday: 0,
    pingsDate: "",
    ignoreStreak: 0,
    preferredHour: 17,
    lastPlayedAt: new Date(Date.now() - 2 * 864e5).toISOString(),
    openToChallenges: true,
    dmPrivacy: "everyone",
    hideFromCatalog: false,
    age: 26,
    gender: "woman" as const,
    ethnicity: "Asian",
    neighborhood: "UT / Hyde Park",
    challengesToday: 0,
    challengesDate: "",
    dmFirstToday: 0,
    dmFirstDate: "",
    rankLastWeek: 6,
    pointsScored: 1100,
    pointsAllowed: 980,
    weeklyWins: 3,
    weeklyLosses: 1,
    ratingLastWeek: 1660,
  },
  {
    id: "p-devon",
    photoUrl: "/players/p-devon.jpg?v=fb3",
    name: "Devon Brooks",
    handle: "dbrooks",
    city: "Austin",
    heightIn: 79,
    weightLb: 220,
    experienceYears: 12,
    rating: 1960,
    gamesPlayed: 80,
    sportsmanship: 4.2,
    reliability: 4.0,
    wins: 58,
    losses: 22,
    streak: -1,
    homeCourtId: "cat-bartholomew",
    availability: "busy",
    bio: "Big wing. Prefer 6'3\"+.",
    hue: 12,
    quietStart: 22,
    quietEnd: 9,
    pingsToday: 0,
    pingsDate: "",
    ignoreStreak: 2,
    preferredHour: 20,
    lastPlayedAt: new Date(Date.now() - 3 * 864e5).toISOString(),
    openToChallenges: true,
    dmPrivacy: "everyone",
    hideFromCatalog: false,
    age: 30,
    gender: "man" as const,
    ethnicity: "Black",
    neighborhood: "East Austin",
    challengesToday: 0,
    challengesDate: "",
    dmFirstToday: 0,
    dmFirstDate: "",
    rankLastWeek: 2,
    pointsScored: 1720,
    pointsAllowed: 1400,
    weeklyWins: 1,
    weeklyLosses: 2,
    ratingLastWeek: 1980,
  },
  {
    id: "p-cam",
    photoUrl: "/players/p-cam.jpg?v=fb3",
    name: "Cam Ortiz",
    handle: "camo",
    city: "Austin",
    heightIn: 71,
    weightLb: 168,
    experienceYears: 3,
    rating: 1490,
    gamesPlayed: 18,
    sportsmanship: 4.5,
    reliability: 4.2,
    wins: 18,
    losses: 17,
    streak: 0,
    homeCourtId: "cat-battle-bend",
    availability: "available",
    bio: "Weekend warrior. Bring a ball.",
    hue: 145,
    quietStart: 23,
    quietEnd: 8,
    pingsToday: 0,
    pingsDate: "",
    ignoreStreak: 0,
    preferredHour: 10,
    lastPlayedAt: new Date(Date.now() - 5 * 864e5).toISOString(),
    openToChallenges: true,
    dmPrivacy: "everyone",
    hideFromCatalog: false,
    age: 25,
    gender: "man" as const,
    ethnicity: "Latino",
    neighborhood: "Downtown",
    challengesToday: 0,
    challengesDate: "",
    dmFirstToday: 0,
    dmFirstDate: "",
    rankLastWeek: 10,
    pointsScored: 380,
    pointsAllowed: 410,
    weeklyWins: 1,
    weeklyLosses: 2,
    ratingLastWeek: 1510,
  },
  {
    id: "p-riley",
    photoUrl: "/players/p-riley.jpg?v=fb3",
    name: "Riley Cho",
    handle: "rcho",
    city: "Austin",
    heightIn: 74,
    weightLb: 178,
    experienceYears: 5,
    rating: 1625,
    gamesPlayed: 35,
    sportsmanship: 4.9,
    reliability: 4.6,
    wins: 27,
    losses: 15,
    streak: 4,
    homeCourtId: "cat-reed",
    availability: "available",
    bio: "Lockdown defense, team-first 1v1.",
    hue: 210,
    quietStart: 22,
    quietEnd: 7,
    pingsToday: 0,
    pingsDate: "",
    ignoreStreak: 0,
    preferredHour: 19,
    lastPlayedAt: new Date(Date.now() - 7 * 864e5).toISOString(),
    openToChallenges: true,
    dmPrivacy: "everyone",
    hideFromCatalog: false,
    age: 28,
    gender: "man" as const,
    ethnicity: "Asian",
    neighborhood: "Domain",
    challengesToday: 0,
    challengesDate: "",
    dmFirstToday: 0,
    dmFirstDate: "",
    rankLastWeek: 8,
    pointsScored: 900,
    pointsAllowed: 820,
    weeklyWins: 4,
    weeklyLosses: 0,
    ratingLastWeek: 1580,
  },
  {
    id: "p-andre",
    photoUrl: "/players/p-andre.jpg?v=fb3",
    name: "Andre Kline",
    handle: "akline",
    city: "Austin",
    heightIn: 81,
    weightLb: 235,
    experienceYears: 11,
    rating: 2010,
    gamesPlayed: 92,
    sportsmanship: 3.9,
    reliability: 4.3,
    wins: 64,
    losses: 28,
    streak: 2,
    homeCourtId: "cat-zaragoza",
    availability: "available",
    bio: "Paint monster. Don’t soft-call.",
    hue: 35,
    quietStart: 0,
    quietEnd: 6,
    pingsToday: 0,
    pingsDate: "",
    ignoreStreak: 0,
    preferredHour: 21,
    lastPlayedAt: new Date(Date.now() - 10 * 864e5).toISOString(),
    openToChallenges: true,
    dmPrivacy: "everyone",
    hideFromCatalog: false,
    age: 32,
    gender: "man" as const,
    ethnicity: "Black",
    neighborhood: "East Austin",
    challengesToday: 0,
    challengesDate: "",
    dmFirstToday: 0,
    dmFirstDate: "",
    rankLastWeek: 4,
    pointsScored: 1900,
    pointsAllowed: 1550,
    weeklyWins: 2,
    weeklyLosses: 1,
    ratingLastWeek: 1990,
  },
  {
    id: "p-sam",
    photoUrl: "/players/p-sam.jpg?v=fb3",
    name: "Sam Patel",
    handle: "spatel",
    city: "Austin",
    heightIn: 70,
    weightLb: 160,
    experienceYears: 2,
    rating: 1380,
    gamesPlayed: 12,
    sportsmanship: 4.7,
    reliability: 4.4,
    wins: 9,
    losses: 11,
    streak: -2,
    availability: "available",
    bio: "Learning the ladder. Fun first.",
    hue: 310,
    quietStart: 22,
    quietEnd: 8,
    pingsToday: 0,
    pingsDate: "",
    ignoreStreak: 0,
    preferredHour: 16,
    lastPlayedAt: new Date(Date.now() - 12 * 864e5).toISOString(),
    openToChallenges: true,
    dmPrivacy: "everyone",
    hideFromCatalog: false,
    age: 27,
    gender: "man" as const,
    ethnicity: "South Asian",
    neighborhood: "North Austin",
    challengesToday: 0,
    challengesDate: "",
    dmFirstToday: 0,
    dmFirstDate: "",
    rankLastWeek: 11,
    pointsScored: 250,
    pointsAllowed: 310,
    weeklyWins: 0,
    weeklyLosses: 2,
    ratingLastWeek: 1410,
  },
  {
    id: "p-tess",
    photoUrl: "/players/p-tess.jpg?v=fb3",
    name: "Tess Rivera",
    handle: "tessr",
    city: "Austin",
    heightIn: 67,
    weightLb: 140,
    experienceYears: 4,
    rating: 1580,
    gamesPlayed: 28,
    sportsmanship: 4.8,
    reliability: 4.9,
    wins: 22,
    losses: 16,
    streak: 1,
    homeCourtId: "cat-little-stacy",
    availability: "busy",
    bio: "Floater game. South Austin parks.",
    hue: 340,
    quietStart: 21,
    quietEnd: 7,
    pingsToday: 0,
    pingsDate: "",
    ignoreStreak: 0,
    preferredHour: 18,
    lastPlayedAt: new Date(Date.now() - 14 * 864e5).toISOString(),
    openToChallenges: true,
    dmPrivacy: "everyone",
    hideFromCatalog: false,
    age: 34,
    gender: "woman" as const,
    ethnicity: "White",
    neighborhood: "South Austin",
    challengesToday: 0,
    challengesDate: "",
    dmFirstToday: 0,
    dmFirstDate: "",
    rankLastWeek: 7,
    pointsScored: 720,
    pointsAllowed: 680,
    weeklyWins: 2,
    weeklyLosses: 1,
    ratingLastWeek: 1550,
  },
  {
    id: "p-noah",
    payCashApp: "noahhoops",

    photoUrl: "/players/p-noah.jpg?v=fb3",
    name: "Noah Bennett",
    handle: "nben",
    city: "Austin",
    heightIn: 75,
    weightLb: 190,
    experienceYears: 7,
    rating: 1755,
    gamesPlayed: 48,
    sportsmanship: 4.4,
    reliability: 4.6,
    wins: 36,
    losses: 20,
    streak: 0,
    homeCourtId: "cat-battle-bend",
    availability: "available",
    bio: "Evenings at Zilker / Battle Bend.",
    hue: 170,
    quietStart: 23,
    quietEnd: 8,
    pingsToday: 0,
    pingsDate: "",
    ignoreStreak: 0,
    preferredHour: 19,
    lastPlayedAt: new Date(Date.now() - 1 * 864e5).toISOString(),
    openToChallenges: true,
    dmPrivacy: "everyone",
    hideFromCatalog: false,
    age: 24,
    gender: "man" as const,
    ethnicity: "White",
    neighborhood: "UT / Hyde Park",
    challengesToday: 0,
    challengesDate: "",
    dmFirstToday: 0,
    dmFirstDate: "",
    rankLastWeek: 5,
    pointsScored: 1200,
    pointsAllowed: 1050,
    weeklyWins: 3,
    weeklyLosses: 0,
    ratingLastWeek: 1720,
  },
  {
    id: "p-kai",
    photoUrl: "/players/p-kai.jpg?v=fb3",
    name: "Kai Thompson",
    handle: "kait",
    city: "Austin",
    heightIn: 78,
    weightLb: 210,
    experienceYears: 9,
    rating: 1895,
    gamesPlayed: 70,
    sportsmanship: 4.6,
    reliability: 4.7,
    wins: 47,
    losses: 18,
    streak: 6,
    homeCourtId: "cat-northwest",
    availability: "available",
    bio: "Stretch four in a 1v1 suit.",
    hue: 240,
    quietStart: 22,
    quietEnd: 7,
    pingsToday: 0,
    pingsDate: "",
    ignoreStreak: 0,
    preferredHour: 20,
    lastPlayedAt: new Date(Date.now() - 4 * 864e5).toISOString(),
    openToChallenges: true,
    dmPrivacy: "everyone",
    hideFromCatalog: false,
    age: 26,
    gender: "man" as const,
    ethnicity: "Black",
    neighborhood: "Domain",
    challengesToday: 0,
    challengesDate: "",
    dmFirstToday: 0,
    dmFirstDate: "",
    rankLastWeek: 4,
    pointsScored: 1650,
    pointsAllowed: 1280,
    weeklyWins: 5,
    weeklyLosses: 0,
    ratingLastWeek: 1850,
  },
];
