import type { Player } from "./types";

/** Seeded Austin 1v1 ladder — demo-quality, local-first. */
export const AUSTIN_PLAYERS: Player[] = [
  {
    id: "p-you",
    name: "You",
    handle: "you",
    city: "Austin",
    heightIn: 72,
    rating: 1520,
    sportsmanship: 4.6,
    wins: 12,
    losses: 8,
    form: 68,
    availability: "available",
    bio: "Looking for clean 1v1 runs after work.",
    hue: 22,
  },
  {
    id: "p-marcus",
    name: "Marcus Hale",
    handle: "mhale",
    city: "Austin",
    heightIn: 76,
    rating: 1840,
    sportsmanship: 4.8,
    wins: 41,
    losses: 14,
    form: 82,
    availability: "available",
    bio: "Post-ups & midrange. Fair fouls only.",
    hue: 198,
  },
  {
    id: "p-jia",
    name: "Jia Nguyen",
    handle: "jia_n",
    city: "Austin",
    heightIn: 68,
    rating: 1710,
    sportsmanship: 5.0,
    wins: 33,
    losses: 19,
    form: 75,
    availability: "available",
    bio: "Handles & threes. Quiet competitor.",
    hue: 280,
  },
  {
    id: "p-devon",
    name: "Devon Brooks",
    handle: "dbrooks",
    city: "Austin",
    heightIn: 79,
    rating: 1960,
    sportsmanship: 4.2,
    wins: 58,
    losses: 22,
    form: 88,
    availability: "busy",
    bio: "Big wing. Prefer 6'3\"+.",
    hue: 12,
  },
  {
    id: "p-cam",
    name: "Cam Ortiz",
    handle: "camo",
    city: "Austin",
    heightIn: 71,
    rating: 1490,
    sportsmanship: 4.5,
    wins: 18,
    losses: 17,
    form: 61,
    availability: "available",
    bio: "Weekend warrior. Bring a ball.",
    hue: 145,
  },
  {
    id: "p-riley",
    name: "Riley Cho",
    handle: "rcho",
    city: "Austin",
    heightIn: 74,
    rating: 1625,
    sportsmanship: 4.9,
    wins: 27,
    losses: 15,
    form: 71,
    availability: "available",
    bio: "Lockdown defense, team-first 1v1.",
    hue: 210,
  },
  {
    id: "p-andre",
    name: "Andre Kline",
    handle: "akline",
    city: "Austin",
    heightIn: 81,
    rating: 2010,
    sportsmanship: 3.9,
    wins: 64,
    losses: 28,
    form: 90,
    availability: "available",
    bio: "Paint monster. Don’t soft-call.",
    hue: 35,
  },
  {
    id: "p-sam",
    name: "Sam Patel",
    handle: "spatel",
    city: "Austin",
    heightIn: 70,
    rating: 1380,
    sportsmanship: 4.7,
    wins: 9,
    losses: 11,
    form: 55,
    availability: "available",
    bio: "Learning the ladder. Fun first.",
    hue: 310,
  },
  {
    id: "p-tess",
    name: "Tess Rivera",
    handle: "tessr",
    city: "Austin",
    heightIn: 67,
    rating: 1580,
    sportsmanship: 4.8,
    wins: 22,
    losses: 16,
    form: 73,
    availability: "busy",
    bio: "Floater game. South Austin parks.",
    hue: 340,
  },
  {
    id: "p-noah",
    name: "Noah Bennett",
    handle: "nben",
    city: "Austin",
    heightIn: 75,
    rating: 1755,
    sportsmanship: 4.4,
    wins: 36,
    losses: 20,
    form: 79,
    availability: "available",
    bio: "Evenings at Zilker / Battle Bend.",
    hue: 170,
  },
  {
    id: "p-lex",
    name: "Lex Morales",
    handle: "lexm",
    city: "Austin",
    heightIn: 73,
    rating: 1660,
    sportsmanship: 4.1,
    wins: 29,
    losses: 24,
    form: 66,
    availability: "offline",
    bio: "Physical ISO ball.",
    hue: 50,
  },
  {
    id: "p-kai",
    name: "Kai Thompson",
    handle: "kait",
    city: "Austin",
    heightIn: 78,
    rating: 1895,
    sportsmanship: 4.6,
    wins: 47,
    losses: 18,
    form: 85,
    availability: "available",
    bio: "Stretch four in a 1v1 suit.",
    hue: 240,
  },
];
